### ISSUE TITLE
error on table journal creation 

### ISSUE THREAD

**Issue by joprice** [fiscaltec/DbUpX#3]
When creating the journal table with `JournalToSqlWithHashing`, I get the error below, whereas plain DbUp works on this step. My first hunch is that it's related to postgres support. If that's the case, is DbUpX intended to work with postgres?

```
Script block number: -1; Message: 42601: syntax error at or near "["

POSITION: 14
Npgsql.PostgresException (0x80004005): 42601: syntax error at or near "["

POSITION: 14
   at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
```

**Comment by shtefanntz** [comment]
Yup, i've hit the same error and i've got the same question :(
